# Generated by Django 4.1.5 on 2023-01-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('CryptoId', models.AutoField(primary_key=True, serialize=False)),
                ('CryptoIcon', models.CharField(max_length=100)),
                ('CryptoName', models.CharField(max_length=100)),
                ('CryptoAbbreviation', models.CharField(max_length=100)),
                ('CryptoCurrentPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('WalletId', models.AutoField(primary_key=True, serialize=False)),
                ('WalletVault', models.FloatField()),
                ('WalletBTC', models.FloatField()),
                ('WalletETH', models.FloatField()),
                ('WalletUSDT', models.FloatField()),
                ('WalletBUSD', models.FloatField()),
                ('WalletSOL', models.FloatField()),
                ('WalletGALA', models.FloatField()),
                ('WalletXRP', models.FloatField()),
                ('WalletADA', models.FloatField()),
                ('WalletLTC', models.FloatField()),
                ('WalletDOGE', models.FloatField()),
                ('WalletBNB', models.FloatField()),
                ('WalletZIL', models.FloatField()),
                ('WalletMATIC', models.FloatField()),
                ('WalletAVAX', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserRole', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('UserSurname', models.CharField(max_length=100)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserProfileURL', models.CharField(max_length=255)),
                ('UserFacebookURL', models.CharField(max_length=255)),
                ('UserInstagramURL', models.CharField(max_length=255)),
                ('UserTwitterURL', models.CharField(max_length=255)),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserWallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionActionType', models.CharField(max_length=100)),
                ('TransactionCryptoType', models.CharField(max_length=100)),
                ('TransactionAmount', models.FloatField()),
                ('TransactionTime', models.DateTimeField(auto_now_add=True)),
                ('TransactionsUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
    ]
