# Generated by Django 4.1.5 on 2023-01-18 22:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('CryptoId', models.AutoField(primary_key=True, serialize=False)),
                ('CryptoIcon', models.CharField(max_length=100)),
                ('CryptoName', models.CharField(max_length=100)),
                ('CryptoAbbreviation', models.CharField(max_length=100)),
                ('CryptoCurrentPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserFirstName', models.CharField(max_length=100)),
                ('UserSurname', models.CharField(max_length=100)),
                ('UserEmail', models.CharField(max_length=100, unique=True)),
                ('UserProfileURL', models.CharField(blank=True, max_length=255, null=True)),
                ('UserPassword', models.CharField(max_length=255)),
                ('UserStatus', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('WalletId', models.AutoField(primary_key=True, serialize=False)),
                ('WalletCard', models.CharField(max_length=16)),
                ('WalletVault', models.FloatField(default=0.0)),
                ('WalletBTC', models.FloatField(default=0.0)),
                ('WalletETH', models.FloatField(default=0.0)),
                ('WalletUSDT', models.FloatField(default=0.0)),
                ('WalletBUSD', models.FloatField(default=0.0)),
                ('WalletSOL', models.FloatField(default=0.0)),
                ('WalletGALA', models.FloatField(default=0.0)),
                ('WalletXRP', models.FloatField(default=0.0)),
                ('WalletADA', models.FloatField(default=0.0)),
                ('WalletLTC', models.FloatField(default=0.0)),
                ('WalletDOGE', models.FloatField(default=0.0)),
                ('WalletBNB', models.FloatField(default=0.0)),
                ('WalletZIL', models.FloatField(default=0.0)),
                ('WalletMATIC', models.FloatField(default=0.0)),
                ('WalletAVAX', models.FloatField(default=0.0)),
                ('WalletUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionActionType', models.CharField(max_length=100)),
                ('TransactionCryptoType', models.CharField(max_length=100)),
                ('TransactionAmount', models.FloatField()),
                ('TransactionTime', models.DateTimeField(auto_now_add=True)),
                ('TransactionsUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
